Update all scripts

diff --git a/make_gif b/make_gif
--- a/make_gif
+++ b/make_gif
@@ -34,18 +34,45 @@ set -Eeuo pipefail
 # -----------------------------
 # ----- Program variables -----
 # -----------------------------
-readonly WORKING_DIRECTORY="${PWD}"
+
+readonly SCRIPT_NAME=$(basename "$0")
 readonly TEMP_DIRECTORY="/tmp/.make_gif"
+readonly WORKING_DIRECTORY="${PWD}"
+
+# -----------------------------------------
+# --------------- Functions ---------------
+# -----------------------------------------
+
+#######################################
+# Prints passed error message before premature exit.
+# Prints everything to >&2 (STDERR).
+# Globals:
+#   RED, NC
+#   SCRIPT_NAME
+# Arguments:
+#   $1: error message to print
+# Returns:
+#   none
+#######################################
+exit_script_on_failure() {
+  printf "\n%sError%s: %s\n" "${RED}" "${NC}" "$1" >&2
+  printf "Exiting %s Bash script.\n" "${SCRIPT_NAME}" >&2
+
+  exit 1
+}
 
 # --------------------------------------
 # --------------- Script ---------------
 # --------------------------------------
 
 # Print intro
-readonly scriptName=$(basename "$0")
-echo -e "Starting ${scriptName} BASH script; Copyright (C) 2019 krathalan"
+echo -e "Starting ${SCRIPT_NAME} Bash script; Copyright (C) 2019 krathalan"
 echo -e "This is free software: you are free to change and redistribute it."
 echo -e "There is NO WARRANTY, to the extent permitted by law.\n"
+
+if [[ $(whoami) == "root" ]]; then
+  exit_script_on_failure "This script should NOT be run as root (or sudo)!"
+fi
 
 rm -rf "${TEMP_DIRECTORY}"
 mkdir "${TEMP_DIRECTORY}"
diff --git a/setup_fedora_software b/setup_fedora_software
--- a/setup_fedora_software
+++ b/setup_fedora_software
@@ -54,6 +54,24 @@ installGamingSoftware=false
 # -----------------------------------------
 
 #######################################
+# Prints passed error message before premature exit.
+# Prints everything to >&2 (STDERR).
+# Globals:
+#   RED, NC
+#   SCRIPT_NAME
+# Arguments:
+#   $1: error message to print
+# Returns:
+#   none
+#######################################
+exit_script_on_failure() {
+  printf "\n%sError%s: %s\n" "${RED}" "${NC}" "$1" >&2
+  printf "Exiting %s Bash script.\n" "${SCRIPT_NAME}" >&2
+
+  exit 1
+}
+
+#######################################
 # Prints "Done."
 # Globals:
 #   none
@@ -92,8 +110,9 @@ echo -e "Starting ${scriptName} BASH script; Copyright (C) 2019 krathalan"
 echo -e "This is free software: you are free to change and redistribute it."
 echo -e "There is NO WARRANTY, to the extent permitted by law.\n"
 
-echo -e "This script should NOT be run as root (or sudo)!"
-read -r -p "Press enter when you are ready to continue, or <CTRL+C> to exit: "
+if [[ $(whoami) == "root" ]]; then
+  exit_script_on_failure "This script should NOT be run as root (or sudo)!"
+fi
 
 echo -e "${stepWithColor}. Configuring DNF..."
 
@@ -113,7 +132,7 @@ sudo sed -i "s#enabled=1#enabled=0#g" /etc/yum.repos.d/fedora-updates-modular.re
 print_done
 
 echo -e "${stepWithColor}. Removing unused DNF packages..."
-sudo dnf autoremove -y abrt* cheese gedit gnome-boxes gnome-calendar 
+sudo dnf autoremove -y abrt* cheese gedit gnome-boxes gnome-calendar \
 gnome-documents gnome-maps gnome-photos gnome-software gnome-weather java* \
 qt5-qt* rhythmbox simple-scan sssd* totem totem-plugins
 
@@ -259,4 +278,4 @@ if ! sudo grep -q -i "MOZ_ENABLE_WAYLAND=1" /etc/environment; then
   fi
 fi
 
-echo -e "Reboot your computer now!"
+echo -e "You will need to reboot your computer for some configuration changes to take effect."
diff --git a/system_maintenance b/system_maintenance
--- a/system_maintenance
+++ b/system_maintenance
@@ -36,9 +36,11 @@ set -Eeuo pipefail
 # -----------------------------
 
 # Colors
+readonly RED=$(tput bold && tput setaf 1)
 readonly TURQOISE=$(tput bold && tput setaf 6)
 readonly NC=$(tput sgr0) # No color/turn off all tput attributes
 
+readonly SCRIPT_NAME=$(basename "$0")
 readonly USER_HOME=$(eval echo ~"${HOME}")
 stepCounter=1
 stepWithColor="${TURQOISE}${stepCounter}${NC}"
@@ -46,6 +48,24 @@ stepWithColor="${TURQOISE}${stepCounter}${NC}"
 # -----------------------------------------
 # --------------- Functions ---------------
 # -----------------------------------------
+
+#######################################
+# Prints passed error message before premature exit.
+# Prints everything to >&2 (STDERR).
+# Globals:
+#   RED, NC
+#   SCRIPT_NAME
+# Arguments:
+#   $1: error message to print
+# Returns:
+#   none
+#######################################
+exit_script_on_failure() {
+  printf "\n%sError%s: %s\n" "${RED}" "${NC}" "$1" >&2
+  printf "Exiting %s Bash script.\n" "${SCRIPT_NAME}" >&2
+
+  exit 1
+}
 
 #######################################
 # Prints " done."
@@ -68,12 +88,13 @@ print_done()
 # --------------------------------------
 
 # Print intro
-readonly scriptName=$(basename "$0")
-echo -e "Starting ${scriptName} BASH script; Copyright (C) 2019 krathalan"
+echo -e "Starting ${SCRIPT_NAME} Bash script; Copyright (C) 2019 krathalan"
 echo -e "This is free software: you are free to change and redistribute it."
-echo -e "There is NO WARRANTY, to the extent permitted by law.\n"
+echo -e "There is NO WARRANTY, to the extent permitted by law."
 
-echo -e "This script should NOT be run as root (or sudo)!"
+if [[ $(whoami) == "root" ]]; then
+  exit_script_on_failure "This script should NOT be run as root (or sudo)!"
+fi
 
 echo -e "\n${stepWithColor}. Updating dnf packages..."
 sudo dnf upgrade --refresh
diff --git a/update_dxvk b/update_dxvk
--- a/update_dxvk
+++ b/update_dxvk
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Description: Updates DXVK in /opt.
+# Description: Updates DXVK in ~/.local/bin.
 #
 # Homepage: https://gitlab.com/krathalan
 #
@@ -23,21 +23,48 @@
 # ----- Program variables -----
 # -----------------------------
 
+# Colors
+readonly RED=$(tput bold && tput setaf 1)
+readonly NC=$(tput sgr0) # No color/turn off all tput attributes
+
 readonly DXVK_FILE_PATH="${HOME}/.local/bin"
 readonly RELEASE_NUMBER="$1"
+readonly SCRIPT_NAME=$(basename "$0")
+
+# -----------------------------------------
+# --------------- Functions ---------------
+# -----------------------------------------
+
+#######################################
+# Prints passed error message before premature exit.
+# Prints everything to >&2 (STDERR).
+# Globals:
+#   RED, NC
+#   SCRIPT_NAME
+# Arguments:
+#   $1: error message to print
+# Returns:
+#   none
+#######################################
+exit_script_on_failure() {
+  printf "%sError%s: %s\n" "${RED}" "${NC}" "$1" >&2
+  printf "Exiting %s Bash script.\n" "${SCRIPT_NAME}" >&2
+
+  exit 1
+}
 
 # --------------------------------------
 # --------------- Script ---------------
 # --------------------------------------
 
 # Print intro
-readonly scriptName=$(basename "$0")
-echo -e "Starting ${scriptName} BASH script; Copyright (C) 2019 krathalan"
+echo -e "Starting ${SCRIPT_NAME} Bash script; Copyright (C) 2019 krathalan"
 echo -e "This is free software: you are free to change and redistribute it."
 echo -e "There is NO WARRANTY, to the extent permitted by law.\n"
 
-echo -e "This script should not be run as root (or sudo)!"
-echo -e ""
+if [[ $(whoami) == "root" ]]; then
+  exit_script_on_failure "This script should NOT be run as root (or sudo)!"
+fi
 
 (
   mkdir -p "${DXVK_FILE_PATH}"
