Fix spacing issues, add some color

diff --git a/setup_linux b/setup_linux
--- a/setup_linux
+++ b/setup_linux
@@ -41,6 +41,7 @@ set -Eeuo pipefail
 # Colors
 readonly GREEN=$(tput bold && tput setaf 2)
 readonly RED=$(tput bold && tput setaf 1)
+readonly ORANGE=$(tput sgr0 && tput setaf 3)
 readonly TURQOISE=$(tput bold && tput setaf 6)
 readonly NC=$(tput sgr0) # No color/turn off all tput attributes
 
@@ -68,7 +69,7 @@ installGamingSoftware=false
 #   none
 #######################################
 exit_script_on_failure() {
-  printf "\n%sError%s: %s\n" "${RED}" "${NC}" "$1" >&2
+  printf "\n[%s✖%s] Error: %s\n" "${RED}" "${NC}" "$1" >&2
   printf "Exiting %s Bash script.\n" "${SCRIPT_NAME}" >&2
 
   exit 1
@@ -140,7 +141,7 @@ print_done
 
 update_Qt_Gtk_theme="false"
 if ! grep -qi "QT_QPA_PLATFORMTHEME" /etc/environment; then
-  printf "\n%s. Making Qt apps use your GTK theme...\n" "${stepWithColor}"
+  printf "%s. Making Qt apps use your GTK theme...\n" "${stepWithColor}"
   echo "QT_QPA_PLATFORMTHEME=gtk2" | sudo tee -a /etc/environment > /dev/null
   update_Qt_Gtk_theme="true"
   print_done
@@ -173,7 +174,7 @@ if [[ "${installGamingSoftware}" == "true" ]]; then
 fi
 
 if [[ "${update_Qt_Gtk_theme}" == "true" ]]; then
-  printf "You will need to reboot your computer for Qt applications to start using your Gtk theme.\n"
+  printf "[%s!%s] You will need to reboot your computer for Qt applications to start using your Gtk theme.\n" "${ORANGE}" "${NC}"
 fi
 
 printf "[%s✔%s] Bash script %s complete.\n" "${GREEN}" "${NC}" "${SCRIPT_NAME}"
