Bug fixes

diff --git a/update_wow_addons b/update_wow_addons
--- a/update_wow_addons
+++ b/update_wow_addons
@@ -29,6 +29,9 @@
 
 # This script uses shellcheck: https://www.shellcheck.net/
 
+# Clean up if script is interrupted early
+trap "clean_up && kill 0" SIGINT
+
 # See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
 set -Eeuo pipefail
 
@@ -69,6 +72,12 @@ readonly PATH_TO_WOW_ADDONS="${PATH_TO_WOW}/drive_c/Program Files (x86)/World of
 # -----------------------------------------
 # --------------- Functions ---------------
 # -----------------------------------------
+
+clean_up() 
+{
+  rm -rf "${TMP_DIR_EXTRACT}"
+  rm -rf "${HOME}/Downloads/"*.zip
+}
 
 #######################################
 # Prints passed error message before premature exit.
@@ -144,8 +153,6 @@ for addonFile in "${HOME}/Downloads"/*; do
   fi
 done
 
-wait
-
 # Step 3
 printf "Done.\n\n%s==> Creating compressed backup of old addon files…%s" "${GREEN}" "${NC}"
 
@@ -161,7 +168,6 @@ printf "\nDone.\n\n%s==> Moving fresh addons to World of Warcraft directory…%s
 mkdir -p "${PATH_TO_WOW_ADDONS}"
 
 mv "${TMP_DIR_EXTRACT}"/* "${PATH_TO_WOW_ADDONS}" 
-
-rm -rf "${TMP_DIR_EXTRACT}"
+clean_up
 
 printf "\nDone.\n\n%s==> Script finished with no errors.%s\n" "${GREEN}" "${NC}"
